//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Bid
{
    public int Id { get; set; }
    public double Price { get; set; }
    public int MemberId { get; set; }
    public int JobId { get; set; }

    public virtual Member Member { get; set; }
    public virtual Job Job { get; set; }
}

public partial class Job
{
    public Job()
    {
        this.Member = new HashSet<Member>();
        this.Bid = new HashSet<Bid>();
        this.Post = new HashSet<Post>();
    }

    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Category { get; set; }
    public string Location { get; set; }
    public string AskingPrice { get; set; }
    public int MemberId { get; set; }

    public virtual Member UserWhoCreatedJob { get; set; }
    public virtual ICollection<Member> Member { get; set; }
    public virtual ICollection<Bid> Bid { get; set; }
    public virtual ICollection<Post> Post { get; set; }
}

public partial class Member
{
    public Member()
    {
        this.JobsCreated = new HashSet<Job>();
        this.Job = new HashSet<Job>();
        this.Post = new HashSet<Post>();
        this.Rating = new HashSet<Rating>();
        this.Bid = new HashSet<Bid>();
        this.Tag = new HashSet<Tag>();
    }

    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string UserName { get; set; }
    public bool Admin { get; set; }
    public bool Jobcreator { get; set; }
    public string Telephone { get; set; }

    public virtual ICollection<Job> JobsCreated { get; set; }
    public virtual ICollection<Job> Job { get; set; }
    public virtual ICollection<Post> Post { get; set; }
    public virtual ICollection<Rating> Rating { get; set; }
    public virtual ICollection<Bid> Bid { get; set; }
    public virtual ICollection<Tag> Tag { get; set; }
}

public partial class Post
{
    public int Id { get; set; }
    public string Comment { get; set; }
    public int MemberId { get; set; }
    public int JobId { get; set; }

    public virtual Member Member { get; set; }
    public virtual Job Job { get; set; }
}

public partial class Rating
{
    public int Id { get; set; }
    public int Num { get; set; }
    public int MemberId { get; set; }

    public virtual Member Member { get; set; }
}

public partial class Tag
{
    public int Id { get; set; }
    public string TagWord { get; set; }
    public int MemberId { get; set; }

    public virtual Member Member { get; set; }
}
